const timerSetupDefaultData = {
  workoutSetup: {
    updated: false,
    workoutArray: [
      {
        id: 0,
        setNo: 1,
        workoutNo: 1,
        type: "rest",
        duration: 5,
        start: 0,
        end: 5,
      },
      {
        id: 1,
        setNo: 2,
        workoutNo: 2,
        type: "workout",
        duration: 5,
        start: 5,
        end: 10,
      },
      {
        id: 2,
        setNo: 3,
        workoutNo: 1,
        type: "rest",
        duration: 5,
        start: 10,
        end: 15,
      },
      {
        id: 3,
        setNo: 3,
        workoutNo: 2,
        type: "rest",
        duration: 5,
        start: 15,
        end: 20,
      },
      {
        id: 4,
        setNo: 3,
        workoutNo: 3,
        type: "rest",
        duration: 5,
        start: 20,
        end: 25,
      },
      {
        id: 5,
        setNo: 4,
        workoutNo: 1,
        type: "rest",
        duration: 2,
        start: 25,
        end: 27,
      },
    ],
  },
  prepareTime: {
    title: "Preparation Time",
    subtitle: "Preparation before Start",
    type: "time",
    value: 5,
  },
  workoutTime: {
    title: "Workout Time",
    subtitle: "Duration for  Workout",
    type: "time",
    value: 5,
  },
  restTime: {
    title: "Rest Time",
    subtitle: "Rest between Workouts",
    type: "time",
    value: 5,
  },
  restTimeSets: {
    title: "Rest Time - Sets",
    subtitle: "Rest between Sets",
    type: "number",
    value: 2,
  },
  sets: {
    title: "Sets",
    subtitle: "Set Amount",
    type: "number",
    value: 2,
  },
  workouts: {
    title: "Workouts",
    subtitle: "Workouts per Set",
    type: "number",
    value: 1,
  },
};
export default timerSetupDefaultData;
