const timerSetupDefaultData = {
  workoutSetup: {
    updated: false,
    workoutArray: [
      {
        duration: 5,
        end: 5,
        id: 0,
        setNo: 0,
        start: 0,
        type: "prepare",
        workoutNo: 0,
      },
      {
        duration: 4,
        end: 9,
        id: 1,
        setNo: 1,
        start: 5,
        type: "workout",
        workoutNo: 1,
      },
      {
        duration: 3,
        end: 12,
        id: 2,
        setNo: 1,
        start: 9,
        type: "rest",
        workoutNo: 1,
      },
      {
        duration: 4,
        end: 16,
        id: 3,
        setNo: 1,
        start: 12,
        type: "workout",
        workoutNo: 2,
      },
      {
        duration: 2,
        end: 18,
        id: 4,
        setNo: 1,
        start: 16,
        type: "rest",
        workoutNo: 2,
      },
      {
        duration: 4,
        end: 22,
        id: 5,
        setNo: 2,
        start: 18,
        type: "workout",
        workoutNo: 1,
      },
      {
        duration: 3,
        end: 25,
        id: 6,
        setNo: 2,
        start: 22,
        type: "rest",
        workoutNo: 1,
      },
      {
        duration: 4,
        end: 29,
        id: 7,
        setNo: 2,
        start: 25,
        type: "workout",
        workoutNo: 2,
      },
    ],
    flatListArray: [
      {
        id: 0,
        name: "workout1",
        image: "",
      },
      {
        id: 1,
        name: "workout2",
        image: "",
      },
    ],
  },
  settings: { playSound: true },
  prepareTime: {
    title: "Preparation Time",
    subtitle: "Preparation before Start",
    type: "time",
    value: 5,
  },
  workoutTime: {
    title: "Workout Time",
    subtitle: "Duration for  Workout",
    type: "time",
    value: 4,
  },
  restTime: {
    title: "Rest Time",
    subtitle: "Rest between Workouts",
    type: "time",
    value: 3,
  },
  restTimeSets: {
    title: "Rest Time - Sets",
    subtitle: "Rest between Sets",
    type: "time",
    value: 2,
  },
  sets: {
    title: "Sets",
    subtitle: "Set Amount",
    type: "number",
    value: 2,
  },
  workouts: {
    title: "Workouts",
    subtitle: "Workouts per Set",
    type: "number",
    value: 2,
  },
};
export default timerSetupDefaultData;
